# Personalize your website info here
title:             Allison Schaser
tagline:          'Neuroscientist Studying Parkinson disease with an SLP's Eye'
description:      'Professional Website for Allison Schaser'
url:              http://ajschaser.github.io
author:
  name:           'Allison Schaser'
  url:            https://ajschaser.gitbub.io

## You don't need to modify below this line
paginate:         5

# Custom vars
version:          2.1.0
github:
  repo:           https://github.com/poole/hyde

gems: [jekyll-paginate,jekyll-gist, redcarpet]
paginate: 5
paginate_path: "page:num"

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
baseurl:          /
